apiVersion: v1
kind: Namespace
metadata:
  name: elk

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
          ports:
            - containerPort: 9200
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.8.2
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.8.2
          ports:
            - containerPort: 5601
            
---

apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: elk
spec:
  ports:
    - name: kibana
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: LoadBalancer

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elk
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.8.2
          volumeMounts:
            - name: var-log
              mountPath: /var/log
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
          securityContext:
            runAsUser: 0
          args: ["-c", "/usr/share/filebeat/filebeat.yml", "-e"]
      volumes:
        - name: filebeat-config
          configMap:
            name: filebeat-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.yml: |
      input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
    }
  


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /dev/stdout
    output.elasticsearch:
      hosts: ["logstash:5044"]
