apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-app
  template:
    metadata:
      labels:
        app: curl-app
    spec:
      containers:
      - name: curl-container
        image: radial/busyboxplus:curl
        env:
        - name: A
          value: "chaosecho:80" # replace with your desired value or from ConfigMap/Secret
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
          while true; do
            curl -X POST -H 'Content-Type: application/json' -H 'Cache-Control: no-cache' -i http://$A/echo --data '{ "content": "FRONTEND REQUEST", "hash": "1" }' --silent
            sleep 1
          done

---
# Deployment for chaosecho
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaosecho
  template:
    metadata:
      labels:
        app: chaosecho
    spec:
      containers:
      - name: chaosecho
        image: diunipisocc/chaosecho:1
        env:
        - name: DEPENDS_ON
          value: ""
        - name: TIMEOUT
          value: "10000"
        - name: P_INVOKE
          value: "0"
        - name: P_FAIL
          value: "75"
        - name: P_CRASH
          value: "25"
        ports:
        - containerPort: 80

---

# Service for chaosecho
apiVersion: v1
kind: Service
metadata:
  name: chaosecho
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: chaosecho
